# Generated by Django 5.2.3 on 2025-06-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralmicro',
            name='versao',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topicos',
            name='nome',
            field=models.CharField(max_length=254),
        ),
    ]
