# Generated by Django 5.2.3 on 2025-06-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_centralmicro_versao_alter_topicos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcontrolador',
            name='ip',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='microcontrolador',
            name='token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
