# Generated by Django 5.2.3 on 2025-06-25 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_microcontrolador_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=254)),
                ('jwt_token', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sessão de Cliente',
                'verbose_name_plural': 'Sessões de Clientes',
                'db_table': 'sessao_cliente',
            },
        ),
    ]
