# Generated by Django 5.2.3 on 2025-06-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sessaocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='exercise_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='gym_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='main_muscles',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='plan_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='summary',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
