# Generated by Django 5.2.3 on 2025-06-26 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_treino_exercise_id_alter_treino_gym_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='centralmicro',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='microcontrolador',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topicos',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='treino',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='versaoonline',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
