# Generated by Django 5.2.3 on 2025-06-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_central_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='centralmicro',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='microcontrolador',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topicos',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='versaoonline',
            name='data_atualizacao',
            field=models.DateField(auto_now=True),
        ),
    ]
