# Generated by Django 5.2.3 on 2025-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_central_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='data_atualizacao',
            field=models.DateField(),
        ),
    ]
