# Generated by Django 5.2.3 on 2025-06-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_treino_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='data_atualizacao',
            field=models.DateTimeField(),
        ),
    ]
